title: rust-analyzer
description: "rust-analyzer: building a better Rust IDE"
baseurl: ""
url: "https://rust-analyzer.github.io/"
github_username: rust-analyzer
exclude: 
  - vendor
  - generated_features.adoc

plugins:
- jekyll-asciidoc
- jekyll-redirect-from

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=rouge
    - source-linenums-option=_
    - rouge-style=github
