= 2019 Financial Report
:sectanchors:
:page-layout: post

This is a short financial report for Open Collective money for 2019.

We've got 9933 EUR on open collective after fees.
We've rounded that number up to 10000 (using some funds from this year) and split it into two buckets:

* 80% for Ferrous Systems
* 20% for contributors, not affiliated with Ferrous

Ferrous share went to paying for part of https://github.com/matklad/[@matklad]'s time (thats me!), and for administrative tasks.
The remaining 2000 EUR were payed to https://github.com/flodiebold/[@flodiebold] for implementing and maintaining type inference infrastructure of rust-analyzer.

Our biggest Open Collective sponsors in 2019 were:

* https://www.embark-studios.com/[Embark Studios] (6000EUR)
* https://discordapp.com/[Discord] (1000EUR)

<3

If you use rust-analyzer professionally, consider asking your company to sponsor the development of this project.

As a reminder, we publish https://rust-analyzer.github.io/thisweek[weekly changelog] to report the progress on rust-analyzer.
