= Changelog #252
:sectanchors:
:experimental:
:page-layout: post

Commit: commit:1301e4268f44e404f0a5847ed72a0b4879e253d3[] +
Release: release:2024-09-23[] (`v0.3.2121`)

== New Features

* pr:18135[] add diagnostics for `unsafe_op_in_unsafe_fn`.
* pr:18131[] replace `$crate` in user-visible macro expansions.
* pr:18151[] support `${concat(...)}` metavariable expressions.
* pr:18137[] support `expr_2021` fragment specifiers.

== Fixes

* pr:18136[] (first contribution) don't lint names of `#[no_mangle]` extern functions.
* pr:18128[] don't show lints and quick fixes in code generated by external macros.
* pr:18117[] always cache macro expansion root nodes in `Semantics`.
* pr:18139[] extend `type_variable_table` when index is larger than the table size.
* pr:18146[] remove check that text of `parse_expr_from_str()` matches the produced parsed tree.
* pr:18153[] account for rawness in `$expr` fragments.
* pr:18108[] take `#[cfg_attr]` into account for lint attributes.
* pr:18132[] don't complete `;` in closure return expressions.

== Internal Improvements

* pr:18134[] extend `SourceChangeBuilder` to make make working with `SyntaxEditor` easier.
* pr:18169[] temporarily disable GitHub releases.
