= Changelog #289
:sectanchors:
:experimental:
:page-layout: post

Commit: commit:9fc1b9076cf49c7f54497df9cfa4485a63f14d3e[] +
Release: release:2025-06-09[] (`v0.3.2490`)

== New Features

* pr:19893[] enhance renaming to include identifier variations that are generated by macros.
* pr:19908[] implement completions for `#[diagnostics]`.
* pr:19922[] ddd `dyn` keyword inlay hints.

== Fixes

* pr:19901[] (first contribution) increase the range of the tuple to named struct assists.
* pr:19869[] (first contribution) add diagnostic and quickfix to make private struct fields public.
* pr:19894[] handle cycles in `infer` and `const_param_ty_with_diagnostics`.
* pr:19935[] always emit quickfixes, even when diagnostics are disabled.
* pr:19936[], pr:19949[] stabilize the unlinked file and "JSON is not Rust" diagnostics.
* pr:19932[], pr:19937[] record macro calls in signatures and fields in `ChildBySource` impls.

== Internal Improvements

* pr:19933[] improve parser recovery for macro calls in type bound position.
* pr:19897[] produce `CLOSURE_BINDER` nodes.
* pr:19905[] clean up macro descension.
* pr:19928[] deduplicate some code in proc macro server.
* pr:19914[] add incremental tests checking for `infer` invalidation.
* pr:19915[], pr:19919[], pr:19920[], pr:19921[] try to fix autopublishing workflow.
