name: CI
on:
  push:
    branches:
      - src
  schedule:
    # Every day, to pick up the latest rust-analyzer repo changes.
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0

permissions:
  contents: write

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
        with:
          ruby-version: "3.2.3"

      - run: bundle install && bundle exec jekyll build

      - uses: taiki-e/install-action@9983c65e42da123ff25d1f78505eb6de315aa172 # v2.87.20
        with:
          tool: mdbook@0.5

      - name: Clone the rust-analyzer repository
        run: git clone --depth 1 https://github.com/rust-lang/rust-analyzer

      - name: Update Rust toolchain
        run: rustup update stable

      - name: Build generated.md files
        run: cd rust-analyzer && cargo xtask codegen

      - name: Run mdbook
        run: cd rust-analyzer/docs/book && mdbook build

      - name: Include mdbook output
        run: mv rust-analyzer/docs/book/book _site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: _site
          force_orphan: true
