name: Typos

on:
  workflow_dispatch:
  push:
    branches: [src]
  pull_request:
    branches: [src]

jobs:
  typos:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.34.0
